export interface Website {
  id: string;
  name: string;
  websiteName?: string;
  developer: string;
  description: string;
  longDescription: string;
  rating: number;
  reviewCount: number;
  categories: string[];
  imageUrl: string;
  screenshots: string[];
  url: string;
  size: string;
  version: string;
  updatedAt: string;
  pricing: "Free" | "Paid" | "Freemium" | "Unknown";
  pros?: string[];
  cons?: string[];
  bestFor?: string;
}

const RAW_SITES = [
  // --- AI & MACHINE LEARNING ---
  { name: "Krea AI", title: "Real-time AI Art Generator", url: "https://krea.ai", cat: ["AI", "Creative", "Design"], desc: "Want to see your creative ideas come to life instantly? Krea AI provides a real-time art generation canvas that enhances your sketches and prompts with high-fidelity AI in seconds." },
  { name: "Napkin AI", title: "Text-to-Diagram AI Visualizer", url: "https://napkin.ai", cat: ["AI", "Productivity", "Ideas"], desc: "Struggling to visualize complex ideas? Napkin AI transforms your text-based thoughts into professional diagrams and visuals, helping you communicate ideas more effectively." },
  { name: "OpenRouter", title: "Unified AI Model Gateway", url: "https://openrouter.ai", cat: ["AI", "Coding", "Developer"], desc: "Need access to the latest AI models without managing multiple accounts? OpenRouter provides a unified API to connect with GPT-4, Claude, and Llama, letting you compare performance and costs in one place." },
  { name: "Jan", title: "Private Local AI Assistant", url: "https://jan.ai", cat: ["AI", "Privacy", "Utilities"], desc: "Looking for a private, offline AI assistant? Jan is an open-source alternative that runs entirely on your local hardware, ensuring your data and conversations never leave your device." },
  { name: "LM Studio", title: "Local LLM Execution Suite", url: "https://lmstudio.ai", cat: ["AI", "Developer", "PC Software"], desc: "Want to explore open-source AI on your own computer? LM Studio lets you discover, download, and run local LLMs easily, giving you full control over your AI environment." },
  { name: "FlowGPT", title: "AI Prompt Engineering Library", url: "https://flowgpt.com", cat: ["AI", "AI Directories", "Creative"], desc: "Looking for the perfect prompt to get the most out of AI? FlowGPT is a massive community library where you can find and share optimized prompt engineering techniques for any use case." },
  { name: "Hugging Face", title: "The Machine Learning Community Hub", url: "https://huggingface.co", cat: ["AI", "Developer", "Coding"], desc: "Building the next generation of AI? Hugging Face is the central hub for the machine learning community, offering millions of open-source models, datasets, and demo apps to accelerate development." },
  { name: "Ideogram", title: "AI Typography & Design Tool", url: "https://ideogram.ai", cat: ["AI", "Design", "Creative"], desc: "Need high-quality AI art with perfect text rendering? Ideogram specializes in generative design that integrates typography seamlessly into beautiful illustrations and brand assets." },
  { name: "Perplexity", title: "AI Search & Research Engine", url: "https://perplexity.ai", cat: ["AI", "Search", "Internet"], desc: "Tired of sorting through search results? Perplexity is an AI research assistant that gives you direct, cited answers to complex questions by scanning the live web in real-time." },
  { name: "Poe", title: "Multi-Model AI Chat Platform", url: "https://poe.com", cat: ["AI", "Chat & Community", "Fun"], desc: "Want to chat with all your favorite AI bots in one place? Poe provides a fast, clean interface to interact with models like GPT-4, Claude, and Gemini, while letting you build your own custom bots." },
  { name: "Runway", title: "Generative AI Video Editor", url: "https://runwayml.com", cat: ["AI", "Video", "Creative"], desc: "Ready to create cinematic visuals with AI? Runway offers a professional suite of creative tools for generating and editing videos, providing Hollywood-grade effects for filmmakers and creators." },
  { name: "Leonardo AI", title: "AI Character & Asset Generator", url: "https://leonardo.ai", cat: ["AI", "Design", "Creative"], desc: "Designing game assets or unique brand visuals? Leonardo AI provides an advanced generative suite tailored for high-quality character design, textures, and architectural concepts." },
  { name: "Gamma", title: "AI Presentation & Slide Generator", url: "https://gamma.app", cat: ["AI", "Design", "Productivity"], desc: "Need a professional presentation fast? Gamma uses AI to generate beautiful slide decks, documents, and web pages from a simple prompt, saving you hours of formatting work." },
  { name: "Phind", title: "Intelligent AI Search for Devs", url: "https://phind.com", cat: ["AI", "Coding", "Developer"], desc: "Stuck on a difficult coding problem? Phind is an intelligent search engine optimized for developers, providing detailed answers and code snippets with references to documentation." },
  { name: "Suno", title: "AI High-Fidelity Music Generator", url: "https://suno.com", cat: ["AI", "Music", "Creative"], desc: "Dreaming of creating your own music? Suno lets you generate complete high-fidelity tracks with instruments and vocals in any style just by describing the vibe you want." },
  { name: "ElevenLabs", title: "Realistic AI Voice Synthesis", url: "https://elevenlabs.io", cat: ["AI", "Voice", "Creative"], desc: "Need realistic voiceovers for your projects? ElevenLabs offers industry-leading AI speech synthesis and voice cloning that captures human emotion and nuance with incredible accuracy." },
  { name: "Mistral AI", title: "High-Efficiency LLM Builder", url: "https://mistral.ai", cat: ["AI", "Developer"], desc: "Looking for efficient, high-performance AI? Mistral AI develops powerful open-weight models that provide a balance of speed and intelligence for developers and enterprises." },
  { name: "Groq", title: "Ultra-Fast AI Inference Platform", url: "https://groq.com", cat: ["AI", "Developer"], desc: "Need AI responses at lightning speed? Groq uses specialized LPU hardware to provide ultra-fast inference for LLMs, making real-time AI applications smoother than ever before." },
  { name: "DeepL", title: "Advanced Neural Translation", url: "https://deepl.com", cat: ["AI", "Education", "Languages"], desc: "Want translations that actually sound natural? DeepL uses advanced neural networks to provide context-aware translations that outperform generic tools for professional and creative writing." },
  { name: "Synthesia", title: "AI Video Avatar Generator", url: "https://synthesia.io", cat: ["AI", "Video"], desc: "Creating training or marketing videos? Synthesia lets you generate professional video content with realistic AI avatars that speak 120+ languages, removing the need for cameras or actors." },
  { name: "Midjourney", title: "Premium AI Visual Artistry", url: "https://midjourney.com", cat: ["AI", "Design", "Creative"], desc: "Looking for the highest tier of AI artistry? Midjourney is a premier generative tool famous for creating stunning, award-winning visuals through a vibrant community-driven interface." },
  
  // --- UTILITY TOOLS ---
  { name: "LightPDF", title: "Complete Cloud PDF Editor & Converter", url: "https://lightpdf.com", cat: ["PDF", "Utilities"], desc: "A powerful web-based PDF toolkit that allows users to edit, convert, sign, and OCR PDF documents without installing software.", pros: ["No installation required", "Supports OCR", "Secure processing"], cons: ["Daily limits on free tier"], bestFor: "Users needing quick PDF edits or document conversions.", pricing: "Freemium" },
  { name: "GetConverter", title: "Universal Media & Document Converter", url: "https://getconverter.com", cat: ["Utilities"], desc: "A versatile online conversion tool that handles documents, images, and audio files easily.", pros: ["Simple interface", "Wide format support"], cons: ["Basic feature set"], bestFor: "Fast conversion between common and obscure file formats.", pricing: "Free" },
  { name: "MrFreeTools", title: "Curation of Premium Free Web Tools", url: "https://mrfreetools.com", cat: ["Utilities"], desc: "An extensive directory of hand-picked web tools that are free to use.", pros: ["Well-curated", "Covers many niches"], cons: ["Directory only"], bestFor: "Discovering high-quality free software alternatives.", pricing: "Free" },
  { name: "123Apps", title: "Web-Based Video, Audio & PDF Suite", url: "https://123apps.com", cat: ["Utilities", "Creative"], desc: "A comprehensive collection of web apps for editing video, audio, and PDF files directly in the browser.", pros: ["All-in-one suite", "No signup required"], cons: ["Ad-supported interface"], bestFor: "Occasional media editing tasks.", pricing: "Free" },
  { name: "PrePostSEO", title: "Comprehensive Content & SEO Analysis Toolkit", url: "https://prepostseo.com", cat: ["SEO", "News"], desc: "A professional-grade suite for content creators including plagiarism checkers and domain authority analysis.", pros: ["Deep SEO metrics", "Multiple tool categories"], cons: ["Interface can be cluttered"], bestFor: "Content writers and marketers.", pricing: "Freemium" },
  { name: "TinyWow", title: "Zero-Hassle Free Online Tool Collection", url: "https://tinywow.com", cat: ["Utilities", "Privacy"], desc: "A massive library of tools for PDF, video, and image processing with a strict focus on data privacy.", pros: ["Privacy focused", "Completely free", "No registration"], cons: ["Occasional processing queues"], bestFor: "Privacy-conscious users wanting free power tools.", pricing: "Free" },
  { name: "Tooools", title: "Professional Design & Creative Resources Directory", url: "https://tooools.app", cat: ["Design", "Creative"], desc: "A highly curated directory of the best tools and resources for designers.", pros: ["Beautiful design", "Top-tier curation"], cons: ["Link directory only"], bestFor: "Designers looking for creative assets.", pricing: "Free" },
  { name: "Ninite", title: "Automated Bulk Software Installer for Windows", url: "https://ninite.com", cat: ["PC Software", "Utilities"], desc: "The easiest way to install and update software on Windows in bulk.", pros: ["Saves hours of setup", "Clean installations"], cons: ["Windows only"], bestFor: "Setting up new PCs.", pricing: "Free" },
  { name: "CalSolver", title: "Advanced Mathematical Problem Solver & Calculators", url: "https://calsolver.net", cat: ["Math", "Education"], desc: "A specialized math portal providing step-by-step solutions for complex equations.", pros: ["Step-by-step guides", "Free access"], cons: ["Academic focus only"], bestFor: "Students and engineers.", pricing: "Free" },
  { name: "Replit", title: "Collaborative Cloud IDE & Deployment Platform", url: "https://replit.com", cat: ["Coding", "Developer"], desc: "An instant coding environment that lives in the browser for 50+ languages.", pros: ["Zero setup", "Live collaboration", "Instant deployment"], cons: ["Free tier limits"], bestFor: "Developers prototyping apps.", pricing: "Freemium" },

  // --- GENERAL / INTERESTING / EXPERIMENTAL ---
  { name: "Zoomquilt", title: "The Infinite Zoom Artwork", url: "https://zoomquilt.org", cat: ["Creative", "Interesting", "Fun"], desc: "A legendary collaborative infinite zoom artwork that hypnotically transitions through endless surreal landscapes.", pros: ["Stunning visuals", "No ads", "Works in browser"], cons: ["High bandwidth usage"], bestFor: "Relaxation and digital art discovery.", pricing: "Free" },
  { name: "Origami.me", title: "Comprehensive Origami Resource", url: "https://origami.me", cat: ["Creative", "Home", "Education"], desc: "A complete guide to the art of paper folding, featuring diagram databases, project ideas, and beginner tips.", pros: ["Large project database", "High quality diagrams"], cons: ["Text-heavy layout"], bestFor: "Craft enthusiasts and hobbyists.", pricing: "Free" },
  { name: "Maze.toys", title: "Infinite Digital Maze Playground", url: "https://maze.toys", cat: ["Brain Games", "Fun"], desc: "A unique web experiment that generates digital mazes for you to solve using your mouse or touch screen.", pros: ["Unique mechanics", "Challenging puzzles"], cons: ["Very niche focus"], bestFor: "Puzzle lovers seeking minimalist games.", pricing: "Free" },
  { name: "Entertrained", title: "Gamified Education Portal", url: "https://entertrained.app", cat: ["Education", "Fun", "School"], desc: "A platform that mixes entertainment with training modules to make learning complex subjects more engaging.", pros: ["Engaging UI", "Interactive elements"], cons: ["Limited subjects"], bestFor: "Students looking for fun ways to study.", pricing: "Free" },
  { name: "Universe", title: "Mobile-First Website Creator", url: "https://univer.se", cat: ["Startups", "Design", "Utilities"], desc: "A grid-based website builder designed specifically for mobile devices, allowing anyone to build a site in minutes.", pros: ["Extremely fast", "Mobile-optimized", "Creative freedom"], cons: ["Subscription for custom domains"], bestFor: "Creators needing a fast mobile landing page.", pricing: "Freemium" },
  { name: "Idiottest", title: "Classic Brain Teaser Tests", url: "https://idiottest.net", cat: ["Brain Games", "Fun"], desc: "A collection of tricky logic puzzles and brain teasers designed to test your attention to detail.", pros: ["Quick to play", "Fun group activity"], cons: ["Ad-supported"], bestFor: "Casual gamers and logic fans.", pricing: "Free" },
  { name: "Zperiod", title: "Minimalist Focus & Timer App", url: "https://zperiod.com", cat: ["Productivity", "Utilities"], desc: "A clean, distraction-free timer and task manager built for deep focus and productivity.", pros: ["Zero distractions", "Free to use"], cons: ["Very simple feature set"], bestFor: "People practicing the Pomodoro technique.", pricing: "Free" },
  { name: "ParlerBeads", title: "Bead Art Pattern Archive", url: "https://parlerbeads.net", cat: ["Creative", "Home"], desc: "A community archive for Perler and Fuse bead patterns, allowing users to browse and share creations.", pros: ["Huge pattern library", "Community driven"], cons: ["Simple UI"], bestFor: "DIY crafters and bead artists.", pricing: "Free" },
  { name: "Slow Roads", title: "Zen Driving Simulator", url: "https://slowroads.io", cat: ["Fun", "Interesting"], desc: "A procedurally generated driving simulator that lets you cruise through infinite, peaceful landscapes.", pros: ["Beautiful graphics", "Relaxing vibe", "No goals/stress"], cons: ["Requires decent GPU"], bestFor: "Stress relief and casual browsing.", pricing: "Free" },
  { name: "Oskar Stalberg", title: "Experimental Architecture Toys", url: "https://oskastalberg.com", cat: ["Design", "Fun"], desc: "Interactive web toys by developer Oskar Stalberg, featuring procedural generation and building mechanics.", pros: ["Incredible tech", "Beautifully minimal"], cons: ["More experiments than tools"], bestFor: "Fans of procedural art and Townscaper.", pricing: "Free" },
  { name: "NASA Imagine", title: "High-Energy Astronomy Portal", url: "https://imagine.gsfc.nasa.gov", cat: ["Science", "Space", "Education"], desc: "NASA's dedicated site for teaching about the universe, high-energy astronomy, and cosmic mysteries.", pros: ["Authentic NASA data", "Rich learning material"], cons: ["Academic design"], bestFor: "Science teachers and space fans.", pricing: "Free" },
  { name: "Goodies Box", title: "Small Web Tools Collection", url: "https://alittleboxofgoodies.com", cat: ["Utilities", "Interesting"], desc: "A curated collection of small, useful, and quirky web tools and links found across the internet.", pros: ["Discover hidden gems", "Varied content"], cons: ["Inconsistent updates"], bestFor: "Internet explorers and tool hunters.", pricing: "Free" },
  { name: "EverythingMoe", title: "The Ultimate Anime Directory", url: "https://everythingmoe.com", cat: ["Anime", "Entertainment", "Interesting"], desc: "A massive, community-vetted directory of the best anime streaming, news, and resource sites on the web.", pros: ["Well categorized", "Clean UI", "Safety vetted"], cons: ["Niche audience"], bestFor: "Anime fans looking for high-quality resources.", pricing: "Free" },

  // --- DIY / ENGINEERING / MAKING ---
  { name: "iFixit", title: "The Free Repair Guide for Everything", url: "https://ifixit.com", cat: ["Utilities", "Utilities"], desc: "A massive community-driven repair manual that provides step-by-step guides for fixing electronics, cars, and home appliances.", pros: ["Huge database", "High-quality photos", "Community help"], cons: ["Replacement parts can be costly"], bestFor: "Users looking to repair their own devices and reduce electronic waste.", pricing: "Free" },
  { name: "ManualsLib", title: "The Ultimate Device Manual Database", url: "https://manualslib.com", cat: ["Utilities", "Utilities"], desc: "A searchable database of over 8 million PDF manuals for consumer electronics and industrial equipment.", pros: ["Massive library", "Searchable content", "Direct PDF downloads"], cons: ["Ad-supported interface"], bestFor: "Finding lost manuals for old or second-hand gadgets.", pricing: "Free" },
  { name: "BookBolt", title: "Low-Content Book Publishing Suite", url: "https://bookbolt.io", cat: ["Creative", "Design", "Productivity"], desc: "A comprehensive toolkit for creating and scaling a book publishing business on Amazon KDP without writing a word.", pros: ["Keyword research tools", "Interior designer", "Cover creator"], cons: ["Subscription required for full features"], bestFor: "Entrepreneurs interested in passive income through niche journal publishing.", pricing: "Paid" },
  { name: "FreeSewing", title: "Open-Source Custom Pattern Generator", url: "https://freesewing.org", cat: ["Creative", "Design"], desc: "An open-source platform that generates custom-made sewing patterns based on your exact body measurements.", pros: ["Perfect fit patterns", "Open source", "Collaborative community"], cons: ["Steep learning curve for beginners"], bestFor: "Home sewists looking for tailored, professional-grade clothing patterns.", pricing: "Free" },
  { name: "Brik", title: "LEGO Inspired Art & Design Studio", url: "https://brik.space", cat: ["Creative", "Fun", "Home"], desc: "A creative platform for designing and sharing pixel-art mosaics using brick-based building blocks.", pros: ["Interactive canvas", "Community designs", "Physical kits available"], cons: ["Best experienced with physical Brik tiles"], bestFor: "Lego fans and pixel artists creating custom home decor.", pricing: "Free" },
  { name: "3DSVG", title: "Intricate 3D Paper Craft Designs", url: "https://3dsvg.com", cat: ["Creative", "Design"], desc: "A premier source for high-quality SVG files used to create complex 3D paper crafts with cutting machines like Cricut.", pros: ["Stunning 3D designs", "Video tutorials", "Precise cut files"], cons: ["Requires a digital cutting machine"], bestFor: "Paper crafters looking to create professional-grade gifts and decor.", pricing: "Paid" },
  { name: "Tinkercad", title: "Simple 3D Design & Circuit Simulation", url: "https://tinkercad.com", cat: ["Design", "Education", "Engineering"], desc: "Autodesk's free, web-based tool for beginners to learn 3D design, electronics, and coding.", pros: ["Extremely beginner friendly", "Runs in browser", "Integrated circuit simulator"], cons: ["Limited for professional engineering"], bestFor: "Students and hobbyists starting with 3D printing and basic electronics.", pricing: "Free" },

  // --- FASHION / CLOTHING ---
  { name: "Tailornova", title: "3D Visual Fashion Design Software", url: "https://tailornova.com", cat: ["Design", "Creative"], desc: "A powerful web-based fashion design platform that lets you create unlimited designs with 3D avatars and custom patterns.", pros: ["3D visualization", "Instant pattern generation", "Vast design library"], cons: ["Professional features are paid"], bestFor: "Fashion designers and students prototyping garments quickly.", pricing: "Freemium" },

  // --- MUSIC ---
  { name: "Hooktheory", title: "Music Theory & Chord Progression Tool", url: "https://hooktheory.com", cat: ["Music", "Education"], desc: "An intelligent platform that uses data from thousands of popular songs to help you write better melodies and chord progressions.", pros: ["Intuitive workflow", "Great for learning theory", "Interactive song database"], cons: ["Advanced tools require purchase"], bestFor: "Songwriters and producers looking to level up their compositions.", pricing: "Freemium" },
  { name: "Radio Garden", title: "Live Global Radio Explorer", url: "https://radio.garden", cat: ["Music", "Entertainment", "Interesting"], desc: "An interactive globe that lets you listen to thousands of live radio stations across the world by rotating the earth.", pros: ["Fascinating discovery", "High performance", "Completely unique UI"], cons: ["Occasional dead streams"], bestFor: "Music lovers and travelers wanting to hear what's playing in any city on Earth.", pricing: "Free" },
  { name: "MyInstants", title: "The World's Largest Instant Soundboard", url: "https://myinstants.com", cat: ["Fun", "Entertainment", "Music"], desc: "A massive library of instant sound buttons and memes used for streaming, chat, and simple fun.", pros: ["Huge variety", "Fast search", "Easy to share"], cons: ["Ad-heavy interface"], bestFor: "Streamers and users looking for quick audio reactions.", pricing: "Free" },
  { name: "Drive & Listen", title: "Virtual Driving & Local Radio Experience", url: "https://driveandlisten.com", cat: ["Entertainment", "Interesting", "Fun"], desc: "An immersive web app that lets you virtually drive through major cities while listening to their local radio stations.", pros: ["Incredibly relaxing", "High-quality video", "Authentic atmosphere"], cons: ["Limited city list"], bestFor: "ASMR fans and people missing the feeling of urban exploration.", pricing: "Free" },
  
  // --- FOOD / RECIPES ---
  { name: "JustTheRecipe", title: "Clutter-Free Recipe View", url: "https://justtherecipe.com", cat: ["Food"], desc: "Instantly extracts recipes from cluttered blogs, leaving only the ingredients and instructions.", pros: ["No ads", "Fast loading", "Mobile friendly"], cons: ["Requires URL input"], bestFor: "Cooks who hate long blog intros.", pricing: "Free" },
  { name: "RecipeScal", title: "Smart Recipe Scaling Tool", url: "https://recipescal.com", cat: ["Food"], desc: "Automatically adjusts recipe portions and measurements for different serving sizes.", pros: ["Precise calculations", "Supports multiple units"], cons: ["Simple UI"], bestFor: "Home chefs hosting large groups.", pricing: "Free" },
  { name: "TasteAtlas", title: "World Food & Flavor Encyclopedia", url: "https://www.tasteatlas.com", cat: ["Food", "Travel"], desc: "A massive interactive map of the world's most authentic local dishes and restaurants.", pros: ["Deep cultural insights", "High-quality photos"], cons: ["Can be overwhelming"], bestFor: "Foodies planning their next trip.", pricing: "Free" },
  { name: "HackTheMenu", title: "Fast Food Secret Menu Database", url: "https://hackthemenu.com", cat: ["Food", "Fun"], desc: "The ultimate guide to secret menu items at every major fast-food chain.", pros: ["Huge database", "Step-by-step ordering"], cons: ["Chain-specific"], bestFor: "Casual diners looking for something new.", pricing: "Free" },

  // --- TRAVEL / MAPS ---
  { name: "WiFi Map", title: "Global Free WiFi Hotspot Finder", url: "https://wifimap.io", cat: ["Travel", "Utilities"], desc: "Crowdsourced database of millions of free WiFi hotspots and passwords worldwide.", pros: ["Huge offline maps", "Community driven"], cons: ["Ad-supported mobile app"], bestFor: "Budget travelers and digital nomads.", pricing: "Freemium" },
  { name: "City Roads", title: "Minimalist City Map Art Generator", url: "https://anvaka.github.io/city-roads/", cat: ["Travel", "Design"], desc: "Visualizes every single road in any city as beautiful minimalist line art.", pros: ["Stunning aesthetics", "High customization"], cons: ["Exporting takes time"], bestFor: "Designers and map enthusiasts.", pricing: "Free" },
  { name: "Snazzy Maps", title: "Custom Styled Google Maps Hub", url: "https://snazzymaps.com", cat: ["Travel", "Design", "Developer"], desc: "A repository of custom styles for Google Maps used by designers and developers.", pros: ["Thousands of themes", "Direct code export"], cons: ["For developers mostly"], bestFor: "Web designers styling location pages.", pricing: "Free" },
  { name: "Driving Simulator", title: "Global 3D Map Driving Sim", url: "https://framesynthesis.com/drivingsimulator/maps/", cat: ["Travel", "Fun"], desc: "A browser-based simulator that lets you drive anywhere in the world using Google Maps 3D data.", pros: ["Explore any city", "Realistic physics"], cons: ["Requires high bandwidth"], bestFor: "Virtual urban explorers.", pricing: "Free" },

  // --- FINANCE / BUSINESS ---
  { name: "Formia", title: "Modern Conversational Form Builder", url: "https://formia.so", cat: ["Finance", "Startups"], desc: "Create high-converting conversational forms and surveys with a focus on design and UX.", pros: ["Beautiful templates", "Fast setup"], cons: ["Free tier limits"], bestFor: "Startups collecting user data.", pricing: "Freemium" },
  { name: "Versus", title: "The Ultimate Comparison Engine", url: "https://versus.com", cat: ["Finance", "Utilities"], desc: "A data-driven comparison platform for hardware, software, services, and even cities.", pros: ["Pure data points", "No bias"], cons: ["Missing niche items"], bestFor: "Buyers making high-stakes decisions.", pricing: "Free" },
  { name: "Vetted", title: "AI-Powered Product Shopping Guide", url: "https://vetted.ai", cat: ["Finance", "Shopping", "AI"], desc: "Analyzes thousands of reviews to tell you which products are actually worth buying.", pros: ["Deep review analysis", "Price tracking"], cons: ["Limited categories"], bestFor: "Smart shoppers looking for quality.", pricing: "Free" },
  { name: "Diode", title: "Decentralized Web Hosting & Network", url: "https://withdiode.com", cat: ["Finance", "Security", "Developer"], desc: "A decentralized networking stack for building secure, edge-to-edge web applications.", pros: ["High security", "No central servers"], cons: ["Technical setup"], bestFor: "Privacy-focused developers.", pricing: "Freemium" },

  // --- PRIVACY / SECURITY ---
  { name: "Privnote", title: "Self-Destructing Encrypted Notes", url: "https://privnote.com", cat: ["Security", "Privacy"], desc: "Send notes that will self-destruct after being read, ensuring sensitive data stays private.", pros: ["Zero traces", "No signup required"], cons: ["One-time use only"], bestFor: "Sharing passwords or secrets safely.", pricing: "Free" },
  { name: "ToS;DR", title: "Terms of Service Summary & Ratings", url: "https://tosdr.org", cat: ["Security", "Privacy"], desc: "Ratings and summaries for the terms of service and privacy policies of major websites.", pros: ["Easy to read", "Saves time"], cons: ["Community based"], bestFor: "Privacy-conscious internet users.", pricing: "Free" },
  { name: "BehindTheEmail", title: "Identify Trackers Behind Emails", url: "https://behindtheemail.com", cat: ["Security", "Privacy"], desc: "See who is tracking your email opens and what data they are collecting about you.", pros: ["Simple usage", "Clear reports"], cons: ["Niche utility"], bestFor: "Users concerned about inbox privacy.", pricing: "Free" },
  { name: "HackerAI", title: "AI-Driven Smart Contract Security", url: "https://hackerai.co", cat: ["Security", "AI", "Developer"], desc: "Uses artificial intelligence to audit smart contracts and identify potential vulnerabilities.", pros: ["Fast audits", "Updated threats"], cons: ["High technical floor"], bestFor: "Web3 developers and auditors.", pricing: "Freemium" },
  { name: "ExplainShell", title: "Visual Command Line Parser", url: "https://explainshell.com", cat: ["Security", "Coding", "Developer"], desc: "Visualizes exactly what each part of a shell command does using man-page data.", pros: ["Educational", "Prevents errors"], cons: ["Bash only"], bestFor: "Sysadmins and terminal beginners.", pricing: "Free" },

  // --- E-COMMERCE & SHOPPING ---
  { name: "CJdropshipping", title: "Global Dropshipping & Fulfillment Platform", url: "https://cjdropshipping.com/", cat: ["Shopping", "Startups", "Utilities"], desc: "Looking to start or scale a dropshipping store? CJdropshipping helps sellers discover products, source them, connect their stores, manage orders, and fulfill shipments to customers worldwide from one platform." },
];

export const MOCK_WEBSITES: Website[] = Array.from(new Set(RAW_SITES.map(s => s.url)))
  .map((url, index) => {
    const site = RAW_SITES.find(s => s.url === url)!;
    const pricingOptions: ("Paid" | "Freemium" | "Free")[] = ["Paid", "Freemium", "Free"];
    const pricing = site.pricing || pricingOptions[index % pricingOptions.length];

    return {
      id: `site-${index}`,
      name: site.title, // Discovery Title
      websiteName: site.name, // Brand Name
      developer: "Bessites Curator",
      description: site.desc, // Detailed Info
      longDescription: site.desc,
      rating: 4.5 + (Math.random() * 0.5),
      reviewCount: 12 + Math.floor(Math.random() * 100),
      categories: site.cat,
      imageUrl: "", 
      screenshots: [],
      url: site.url,
      size: "N/A",
      version: "1.0",
      updatedAt: "2024",
      pricing: pricing as any,
      pros: (site as any).pros || ["Hand-picked quality", "Verified URL", "Highly useful"],
      cons: (site as any).cons || ["May require account", "Limited free tier"],
      bestFor: (site as any).bestFor || "General users and digital creators."
    };
  });
