export interface Website {
  id: string;
  name: string;
  websiteName?: string;
  developer: string;
  description: string;
  longDescription: string;
  rating: number;
  reviewCount: number;
  categories: string[];
  imageUrl: string;
  screenshots: string[];
  url: string;
  size: string;
  version: string;
  updatedAt: string;
  pricing: "Free" | "Paid" | "Freemium" | "Unknown";
  pros?: string[];
  cons?: string[];
  bestFor?: string;
}

const RAW_SITES = [
  // --- BATCH 1: CORE DISCOVERY ---
  { name: "Aceternity UI", title: "Aceternity UI | Modern Animated Components", url: "https://ui.aceternity.com", cat: ["Developer Tools & UI Kits"], desc: "Aceternity UI is an award-winning collection of modern, copy-paste React and Tailwind CSS components designed for developers who want to build sleek, dark-mode websites.", pricing: "Free", pros: ["High-end animations", "Copy-paste ease", "Modern aesthetic"], cons: ["Tailwind specific", "Framer Motion dependency"], bestFor: "React developers building luxury landing pages." },
  { name: "Spline", title: "Spline 3D Design | Real-Time 3D for the Web", url: "https://spline.design", cat: ["3D Design & Web Graphics"], desc: "Spline is a collaborative browser-based 3D design software that allows creators to build, animate, and publish interactive 3D web experiences without complex code.", pricing: "Freemium", pros: ["Intuitive 3D logic", "Direct React exports", "Real-time physics"], cons: ["High resource usage", "Learning curve"], bestFor: "Designers adding interactive 3D assets to web projects." },
  { name: "Godly", title: "Godly | Top Web Design Inspiration Gallery", url: "https://godly.website", cat: ["Design Inspiration & Curation"], desc: "Godly is a strictly curated design gallery that indexes the top 1% of web design projects worldwide. Updated daily, it serves as the ultimate benchmark for modern typography.", pricing: "Free", pros: ["Daily inspiration", "Elite curation", "Filtered by style"], cons: ["Reference only", "No tools included"], bestFor: "UI/UX designers seeking high-end layout trends." },
  { name: "Radio Garden", title: "Radio Garden | Explore Live Global Radio", url: "https://radio.garden", cat: ["Interactive Web & Audio"], desc: "Radio Garden is a live, interactive 3D globe that lets you explore and listen to thousands of local radio broadcasts worldwide in real time.", pricing: "Free" },
  { name: "Krea AI", title: "Krea AI Studio | Real-Time Creative AI", url: "https://krea.ai", cat: ["Generative AI & Image Generation"], desc: "Krea AI is an ultra-fast generative visual engine offering real-time AI canvas generation, AI video enhancement, and high-fidelity upscaling.", pricing: "Freemium" },
  { name: "Slow Roads", title: "Slow Roads | Procedural Browser Driving Simulator", url: "https://slowroads.io", cat: ["Browser Games & Simulators"], desc: "Slow Roads is a procedurally generated 3D driving simulator that runs entirely inside your web browser using WebGL.", pricing: "Free" },
  { name: "Linear", title: "Linear | The Issue Tracker Built for Speed", url: "https://linear.app", cat: ["Productivity & Project Management"], desc: "Linear is a streamlined issue tracking and product management tool built specifically for high-velocity software engineering and design teams.", pricing: "Freemium" },
  { name: "Neal.fun", title: "Neal.fun | Viral Interactive Web Experiments", url: "https://neal.fun", cat: ["Creative Experiments & Mini Games"], desc: "Neal.fun is a massive collection of viral, high-concept interactive web toys and digital experiments created by designer Neal Agarwal.", pricing: "Free" },
  { name: "Uiverse", title: "Uiverse.io | Open-Source UI Components", url: "https://uiverse.io", cat: ["Open Source CSS & Frontend Assets"], desc: "Uiverse is the web's largest community-driven repository of 100% free, open-source UI micro-components. Pure HTML, CSS, and Tailwind code.", pricing: "Free" },
  { name: "Mobbin", title: "Mobbin | Comprehensive UI/UX Design Reference", url: "https://mobbin.com", cat: ["UI/UX Research & App Architecture"], desc: "Mobbin is the definitive reference library for digital product designers, archiving thousands of fully searchable screenshots and complete user flows.", pricing: "Freemium" },

  // --- BATCH 2: AI & INFRASTRUCTURE ---
  { name: "v0 by Vercel", title: "v0 by Vercel | Generative UI & Full-Stack React Code", url: "https://v0.dev", cat: ["AI Development & Generative Code"], desc: "v0 is a generative user interface system built by Vercel that turns natural language prompts and design screenshots into production-ready React, Next.js, and Tailwind CSS code.", pricing: "Freemium" },
  { name: "Lovable", title: "Lovable | Full-Stack AI Software Engineer", url: "https://lovable.dev", cat: ["AI Development & Generative Code"], desc: "Lovable is an autonomous full-stack AI development platform that builds, tests, and deploys complete web applications from conversational prompts.", pricing: "Freemium" },
  { name: "ElevenLabs", title: "ElevenLabs | Voice AI & Generative Audio", url: "https://elevenlabs.io", cat: ["Voice AI & Audio Synthesis"], desc: "ElevenLabs is the industry-leading generative voice AI platform capable of producing hyper-realistic speech and voice clones.", pricing: "Freemium" },
  { name: "Luma Dream Machine", title: "Luma Dream Machine | Next-Gen Generative AI Video", url: "https://lumalabs.ai/dream-machine", cat: ["Generative AI Video & 3D"], desc: "Dream Machine is a high-speed video generation model that converts text and images into fluid, physically accurate video clips.", pricing: "Freemium" },
  { name: "Supabase", title: "Supabase | The Open-Source Firebase Alternative", url: "https://supabase.com", cat: ["Cloud Backend & Database Infrastructure"], desc: "Supabase provides developers with an open-source backend suite offering dedicated PostgreSQL databases, instant APIs, and real-time sync.", pricing: "Freemium" },
  { name: "Resend", title: "Resend | Modern Email API for Developers", url: "https://resend.com", cat: ["Developer APIs & Infrastructure"], desc: "Resend is an email platform designed specifically for software developers with React Email integration.", pricing: "Freemium" },
  { name: "tldraw", title: "tldraw | Collaborative Infinite Canvas & SDK", url: "https://tldraw.com", cat: ["Visual Workspace & Whiteboarding"], desc: "tldraw is an open-source digital whiteboard and collaborative infinite canvas with an ultra-responsive vector engine.", pricing: "Free" },
  { name: "Typefully", title: "Typefully | Distraction-Free Writing & Social Publishing", url: "https://typefully.com", cat: ["Content Creation & Social Growth"], desc: "Typefully is a minimalist writing canvas and social media scheduling platform built for creators.", pricing: "Freemium" },
  { name: "PostHog", title: "PostHog | All-in-One Product Analytics Suite", url: "https://posthog.com", cat: ["Analytics & User Behavior"], desc: "PostHog is an open-source product analytics platform that combines event tracking, session replays, and heatmaps.", pricing: "Freemium" },
  { name: "ReadCV", title: "ReadCV | Professional Profiles & Creative Network", url: "https://read.cv", cat: ["Portfolios & Professional Networking"], desc: "ReadCV is a minimalist professional network and interactive resume builder tailored for designers, engineers, and creative builders.", pricing: "Free" },

  // --- BATCH 3: SPECIALIZED TOOLS ---
  { name: "Cursor", title: "Cursor | The AI-First Code Editor", url: "https://www.cursor.com", cat: ["Developer Tools & AI IDEs"], desc: "Cursor is an AI-native code editor built as a high-performance fork of VS Code.", pricing: "Freemium" },
  { name: "Perplexity", title: "Perplexity AI | Conversational Answer Engine", url: "https://www.perplexity.ai", cat: ["AI Search & Research Engines"], desc: "Perplexity AI is an interactive conversational answer engine that delivers direct, cited answers.", pricing: "Freemium" },
  { name: "Midjourney", title: "Midjourney | Generative Visual Art Canvas", url: "https://www.midjourney.com", cat: ["Generative AI & Concept Art"], desc: "Midjourney is an AI image generation platform renowned for its photorealistic texturing.", pricing: "Paid" },
  { name: "Pika", title: "Pika Labs | Generative Video & Cinematic Effects", url: "https://pika.art", cat: ["Generative AI Video & 3D"], desc: "Pika is an intuitive browser-based AI video generation and animation platform.", pricing: "Freemium" },
  { name: "Framer", title: "Framer | Interactive Web Design & Publishing", url: "https://www.framer.com", cat: ["No-Code & Web Architecture"], desc: "Framer is a visual website builder that blends canvas design with production-grade web publishing.", pricing: "Freemium" },
  { name: "Veed", title: "Veed.io | In-Browser Video Studio & AI Captions", url: "https://www.veed.io", cat: ["Video Editing & Content Creation"], desc: "Veed is an all-in-one cloud-based video editing platform tailored for digital creators.", pricing: "Freemium" },
  { name: "Playroom", title: "Playroom | Multiplayer Web Game Engine", url: "https://joinplayroom.com", cat: ["Game Development & Interactive Tech"], desc: "Playroom is a multiplayer toolkit that allows indie developers to build synchronized web games in minutes.", pricing: "Free" },
  { name: "Looka", title: "Looka | AI Brand Identity & Logo Maker", url: "https://looka.com", cat: ["Design & Branding"], desc: "Looka is an AI-powered brand generator that translates user preferences into custom vector logos.", pricing: "Paid" },
  { name: "Claude", title: "Claude by Anthropic | Frontier AI Reasoning", url: "https://claude.ai", cat: ["AI Assistants & LLM Interfaces"], desc: "Claude is an advanced conversational AI assistant engineered for complex technical reasoning.", pricing: "Freemium" },
  { name: "Descript", title: "Descript | Document-Based Audio & Video Editor", url: "https://www.descript.com", cat: ["Audio Production & Podcasting"], desc: "Descript is a multimedia editing platform where creators edit audio and video by editing text transcripts.", pricing: "Freemium" },

  // --- BATCH 4: ANIMATION & INFRASTRUCTURE ---
  { name: "GSAP", title: "GSAP | Professional-Grade JavaScript Web Animation", url: "https://gsap.com", cat: ["Web Animation & Creative Coding"], desc: "The industry standard JavaScript animation library powering high-performance motion on 11M+ sites.", pricing: "Free" },
  { name: "Ray.so", title: "Ray.so | Beautiful Code Snippet Screenshot Generator", url: "https://ray.so", cat: ["Developer Utilities & Code Presentation"], desc: "Transforms raw programming code into aesthetic, high-resolution syntax-highlighted images.", pricing: "Free" },
  { name: "Awwwards", title: "Awwwards | Digital Design Recognition & Agency Showcase", url: "https://www.awwwards.com", cat: ["Design Awards & Creative Inspiration"], desc: "The global benchmark platform that recognizes and awards the finest talent in digital design.", pricing: "Free" },
  { name: "Landingfolio", title: "Landingfolio | The Best Landing Page Design Inspiration", url: "https://www.landingfolio.com", cat: ["Landing Page & Conversion Design"], desc: "A curated gallery showcasing high-converting landing page designs.", pricing: "Free" },
  { name: "Coolors", title: "Coolors | Superfast Color Schemes Generator", url: "https://coolors.co", cat: ["Color Tools & UI Design Systems"], desc: "Lightning-fast color palette generator used by millions of designers daily.", pricing: "Free" },
  { name: "Vercel", title: "Vercel | The Frontend Cloud & Next.js Platform", url: "https://vercel.com", cat: ["Cloud Hosting & Deployment Infrastructure"], desc: "The creators of Next.js, providing an end-to-end frontend cloud platform.", pricing: "Freemium" },
  { name: "Figma", title: "Figma | The Collaborative Interface Design Standard", url: "https://www.figma.com", cat: ["Product UI/UX & Vector Design"], desc: "The industry-standard collaborative vector design software.", pricing: "Freemium" },
  { name: "Lucide", title: "Lucide Icons | Beautiful Open-Source Icon Toolkit", url: "https://lucide.dev", cat: ["Vector Graphics & Iconography"], desc: "An open-source, community-run fork of Feather Icons.", pricing: "Free" },
  { name: "Roadmap.sh", title: "Roadmap.sh | Developer Career & Skill Roadmaps", url: "https://roadmap.sh", cat: ["Developer Education & Career Learning"], desc: "Step-by-step visual roadmaps and study guides for software engineers.", pricing: "Free" },
  { name: "Dribbble", title: "Dribbble | The World's Leading Design Portfolio Showcase", url: "https://dribbble.com", cat: ["Design Inspiration & Curation"], desc: "The premier discovery platform for digital product designers.", pricing: "Free" },

  // --- BATCH 5: SPECIALIZED TOOLS ---
  { name: "Bolt.new", title: "Bolt.new | In-Browser Full-Stack AI Web Engineering", url: "https://bolt.new", cat: ["AI Development & Generative Code"], desc: "AI development workspace that executes full-stack production web apps inside your browser.", pricing: "Freemium" },
  { name: "Recraft", title: "Recraft AI | Generative Infinite Vector & 3D Art Studio", url: "https://www.recraft.ai", cat: ["Generative Vector & Brand Illustration"], desc: "Professional generative visual studio that natively outputs vector SVG illustrations.", pricing: "Freemium" },
  { name: "Readymag", title: "Readymag | Editorial Web Design & Digital Publishing", url: "https://readymag.com", cat: ["Editorial & Creative Web Publishing"], desc: "In-browser visual publishing platform crafted for creative directors.", pricing: "Freemium" },
  { name: "Streamline", title: "Streamline Icons | The World's Largest Vector Asset System", url: "https://www.streamlinehq.com", cat: ["Design Assets & Icon Systems"], desc: "Exhaustive design system featuring 170,000+ vector icons.", pricing: "Freemium" },
  { name: "Untitled UI", title: "Untitled UI | The Ultimate Figma UI Kit & Design System", url: "https://www.untitledui.com", cat: ["UI Kits & Design Systems"], desc: "The industry's largest and most widely used Figma UI kit.", pricing: "Paid" },
  { name: "Microsoft Clarity", title: "Microsoft Clarity | Free Behavioral Analytics & Heatmaps", url: "https://clarity.microsoft.com", cat: ["Analytics & User Behavior"], desc: "Free behavioral analytics tool that visualizes user journeys.", pricing: "Free" },
  { name: "Spline AI", title: "Spline AI | Prompt-to-3D Texturing & Scene Generator", url: "https://spline.design/ai", cat: ["3D Design & Web Graphics"], desc: "Generative AI integrated directly into the 3D web design workflow.", pricing: "Freemium" },
  { name: "Uxcel", title: "Uxcel | Interactive UX Design Training", url: "https://uxcel.com", cat: ["Developer Education & Career Learning"], desc: "Gamified learning platform that teaches digital product design.", pricing: "Freemium" },
  { name: "Memberstack", title: "Memberstack | Gated Memberships & Web Auth Engine", url: "https://www.memberstack.com", cat: ["No-Code & Web Architecture"], desc: "Infrastructure layer to add secure logins and subscriptions.", pricing: "Freemium" },
  { name: "Fabric", title: "Fabric | AI-Powered Unified Digital Workspace", url: "https://fabric.so", cat: ["Visual Workspace & Whiteboarding"], desc: "Intelligent workspace that acts as a digital memory hub.", pricing: "Freemium" },

  // --- BATCH 6: ENTERPRISE & AUTOMATION ---
  { name: "TanStack", title: "TanStack | Headless Full-Stack Frameworks", url: "https://tanstack.com", cat: ["Frontend Frameworks & State Architecture"], desc: "Headless, type-safe open-source web utilities.", pricing: "Free" },
  { name: "Zapier", title: "Zapier | Automated Enterprise Workflow Orchestration", url: "https://zapier.com", cat: ["No-Code Databases & Workflow Automation"], desc: "Connects over 6,000 web apps without requiring manual code.", pricing: "Freemium" },
  { name: "Shortwave", title: "Shortwave | AI-Native Email & Productivity System", url: "https://www.shortwave.com", cat: ["Productivity & Time Management"], desc: "Email client designed around the Method of Inbox Zero.", pricing: "Freemium" },
  { name: "Kuberns", title: "Kuberns | Agentic AI Cloud Deployment", url: "https://kuberns.com", cat: ["Cloud Hosting & Deployment Infrastructure"], desc: "Agentic AI cloud deployment platform that automates backend setup.", pricing: "Freemium" },
  { name: "Adobe Firefly", title: "Adobe Firefly | Commercially Safe Generative AI", url: "https://firefly.adobe.com", cat: ["Generative AI & Concept Art"], desc: "Creative generative AI models trained on licensed content.", pricing: "Freemium" },

  // --- BATCH 7: KNOWLEDGE & SANDBOXES ---
  { name: "Glitch", title: "Glitch | Fast In-Browser Web App Creation", url: "https://glitch.com", cat: ["Creative Coding & Social Sandboxes"], desc: "Collaborative coding platform where users build and host web apps.", pricing: "Freemium" },
  { name: "Obsidian", title: "Obsidian | Extensible Markdown Knowledge Graph", url: "https://obsidian.md", cat: ["Knowledge Graphs & Personal Productivity"], desc: "Private, offline-first knowledge management hub.", pricing: "Free" },
  { name: "Shapr3D", title: "Shapr3D | Direct Multi-Device CAD Modeling", url: "https://www.shapr3d.com", cat: ["CAD Engineering & Industrial Design"], desc: "Intuitive direct 3D modeling CAD tool.", pricing: "Freemium" },
  { name: "Codeium", title: "Codeium | Free AI-Powered Code Acceleration", url: "https://codeium.com", cat: ["Developer Tools & AI IDEs"], desc: "Modern AI coding assistant that integrates across IDEs.", pricing: "Free" },
  { name: "Render", title: "Render | Modern Zero-DevOps Cloud Hosting", url: "https://render.com", cat: ["Cloud Hosting & Deployment Infrastructure"], desc: "Unified cloud platform that builds and hosts web apps.", pricing: "Freemium" },

  // --- BATCH 8: INFRASTRUCTURE & COMMERCE ---
  { name: "Stripe", title: "Stripe | Financial Infrastructure for the Internet", url: "https://stripe.com", cat: ["Payments & Global Commerce"], desc: "World's leading financial infrastructure platform.", pricing: "Freemium" },
  { name: "Cloudflare", title: "Cloudflare Workers | Serverless Edge Computing & CDN", url: "https://workers.cloudflare.com", cat: ["Edge Computing & Web Security"], desc: "Lightweight serverless execution environment at the edge.", pricing: "Freemium" },
  { name: "Temporal", title: "Temporal | Durable Execution & Distributed State", url: "https://temporal.io", cat: ["Backend Orchestration & Microservices"], desc: "Open-source workflow orchestration engine.", pricing: "Free" },
  { name: "LaunchDarkly", title: "LaunchDarkly | Feature Flagging & Experimentation", url: "https://launchdarkly.com", cat: ["DevOps & Continuous Delivery"], desc: "Enterprise feature management platform.", pricing: "Paid" },
  { name: "Sentry", title: "Sentry | Real-Time Error Tracking & Code Observability", url: "https://sentry.io", cat: ["Application Monitoring & Observability"], desc: "Real-time error tracking designed for modern apps.", pricing: "Freemium" },
  { name: "WorkOS", title: "WorkOS | Enterprise SSO, SCIM & Directory Sync", url: "https://workos.com", cat: ["Identity & Enterprise Authentication"], desc: "Developer-friendly APIs for enterprise-ready SaaS.", pricing: "Freemium" },
  { name: "Datadog", title: "Datadog | Cloud Monitoring & Security Analytics", url: "https://www.datadoghq.com", cat: ["Application Monitoring & Observability"], desc: "Observability analytics platform for cloud infrastructure.", pricing: "Paid" },
  { name: "HeyGen", title: "HeyGen | Generative AI Video & Photorealistic Avatars", url: "https://www.heygen.com", cat: ["AI Video Generation & Digital Avatars"], desc: "AI video studio that creates spokesperson videos.", pricing: "Freemium" },
  { name: "FastAPI", title: "FastAPI | Modern Python Web Framework", url: "https://fastapi.tiangolo.com", cat: ["Backend APIs & Python Development"], desc: "Fast Python web framework for scalable RESTful APIs.", pricing: "Free" },
  { name: "SurferSEO", title: "SurferSEO | Content Intelligence & SEO Optimization", url: "https://surferseo.com", cat: ["SEO Analytics & Organic Search"], desc: "AI-powered search optimization platform.", pricing: "Paid" },
  { name: "Shopify", title: "Shopify | Global E-Commerce Platform", url: "https://www.shopify.com", cat: ["Payments & Global Commerce"], desc: "Global commerce platform powering online storefronts.", pricing: "Paid" },

  // --- BATCH 9: AUTH & MODERN STACK ---
  { name: "Clerk", title: "Clerk | Complete User Authentication", url: "https://clerk.com", cat: ["Identity & User Authentication"], desc: "Developer-first auth platform for React and Next.js.", pricing: "Freemium" },
  { name: "Upstash", title: "Upstash | Serverless Redis & Kafka", url: "https://upstash.com", cat: ["Serverless Data & Edge Caching"], desc: "Serverless data platform for edge computing.", pricing: "Freemium" },
  { name: "PlanetScale", title: "PlanetScale | Serverless MySQL", url: "https://planetscale.com", cat: ["Cloud Databases & Data Infrastructure"], desc: "Advanced MySQL-compatible serverless database.", pricing: "Paid" },
  { name: "Prisma", title: "Prisma | TypeScript ORM", url: "https://www.prisma.io", cat: ["Backend Tooling & Database ORMs"], desc: "Next-generation ORM toolkit for Node.js.", pricing: "Free" },
  { name: "Biome", title: "Biome | Fast Web Development Toolchain", url: "https://biomejs.dev", cat: ["Developer Utilities & Code Quality"], desc: "High-performance toolchain written in Rust.", pricing: "Free" },
  { name: "Bun", title: "Bun | Fast All-in-One JS Runtime", url: "https://bun.sh", cat: ["Developer Tooling & JavaScript Runtimes"], desc: "All-in-one JavaScript runtime and package manager.", pricing: "Free" },
  { name: "Mintlify", title: "Mintlify | Modern Documentation", url: "https://mintlify.com", cat: ["Developer Documentation & Knowledge Bases"], desc: "MDX-powered documentation engine for startups.", pricing: "Freemium" },
  { name: "Hugging Face", title: "Hugging Face | The Open AI Model Hub", url: "https://huggingface.co", cat: ["AI Models & Open-Source Machine Learning"], desc: "Central collaboration hub for the machine learning ecosystem.", pricing: "Freemium" },
  { name: "Tailwind UI", title: "Tailwind UI | Official Component Library", url: "https://tailwindui.com", cat: ["Frontend Frameworks & Component Blocks"], desc: "Official visual component library by Tailwind Labs.", pricing: "Paid" },

  // --- BATCH 10: VIDEO & CREATIVE UTILS ---
  { name: "Screen Studio", title: "Screen Studio | Professional Screen Recorder for macOS", url: "https://www.screen.studio", cat: ["Video Production & Screen Recording"], desc: "Advanced screen recording software that transforms captures into promotional videos automatically.", pricing: "Paid" },
  { name: "Ollama", title: "Ollama | Run Large Language Models Locally", url: "https://ollama.com", cat: ["Local AI & Machine Learning Tools"], desc: "Open-source framework to run and manage LLMs locally on personal hardware.", pricing: "Free" },
  { name: "Raycast Extensions", title: "Raycast Store | Extensible Developer Plugins", url: "https://www.raycast.com/store", cat: ["Developer Tooling & Desktop Ecosystems"], desc: "Open-source ecosystem of thousands of community-built extensions for Raycast launcher.", pricing: "Free" },
  { name: "Slicknode", title: "Slicknode | Modular Serverless GraphQL Backend Engine", url: "https://slicknode.com", cat: ["Backend APIs & Data Orchestration"], desc: "Serverless GraphQL backend framework combining schema modeling with instant infrastructure.", pricing: "Freemium" },
  { name: "Phosphor Icons", title: "Phosphor Icons | Flexible Icon Family for Interfaces", url: "https://phosphoricons.com", cat: ["Vector Graphics & Iconography"], desc: "Flexible icon family with over 9,000 vector assets across six distinct weights.", pricing: "Free" },
  { name: "OpenStatus", title: "OpenStatus | Open-Source Monitoring & Status Pages", url: "https://www.openstatus.dev", cat: ["Application Monitoring & Observability"], desc: "Modern synthetic monitoring platform and incident status page builder.", pricing: "Freemium" },
  { name: "Fontshare Variable", title: "Fontshare Variable Fonts | Dynamic Axis Explorer", url: "https://www.fontshare.com/variable", cat: ["Typography & Font Discovery"], desc: "Interactive controls to manipulate axes across a curated catalog of free variable fonts.", pricing: "Free" },
  { name: "Resend React Email", title: "React Email | Component Collection for Email Templates", url: "https://react.email", cat: ["Developer APIs & Infrastructure"], desc: "Open-source suite of clean, responsive components for crafting HTML emails with React.", pricing: "Free" },
  { name: "Warp", title: "Warp | AI-Enabled Modern Terminal for Developers", url: "https://www.warp.dev", cat: ["Developer Tools & AI IDEs"], desc: "GPU-accelerated terminal application built in Rust with integrated AI command generation.", pricing: "Freemium" },
  { name: "Jitter Motion Studio", title: "Jitter | Fast Motion Design & UI Animations", url: "https://jitter.video", cat: ["Web Animation & Creative Coding"], desc: "Web-based motion design platform built for animating UI components and typography.", pricing: "Freemium" },
  { name: "V0 UI Blocks", title: "v0 Explore Blocks | Production Component Layouts", url: "https://v0.dev/explore", cat: ["Frontend Frameworks & Component Blocks"], desc: "Curated gallery of modular React UI blocks generated with AI and verified by Vercel.", pricing: "Free" },
  { name: "Uiverse Pure CSS", title: "Uiverse CSS Buttons | Community Micro-Interactions", url: "https://uiverse.io/buttons", cat: ["Open Source CSS & Frontend Assets"], desc: "Expansive sub-library dedicated specifically to copyable interactive button design.", pricing: "Free" },
  { name: "Spline 3D Shaders", title: "Spline Material Shaders | Procedural Glass Generator", url: "https://spline.design/materials", cat: ["3D Design & Web Graphics"], desc: "Create procedural glass and matcap finishes on 3D meshes directly in the browser.", pricing: "Freemium" },
  { name: "Pico CSS", title: "Pico CSS | Minimalist Semantic CSS Framework", url: "https://picocss.com", cat: ["Frontend Frameworks & Styling Tooling"], desc: "Lightweight, semantic CSS framework that styles pure HTML elements automatically.", pricing: "Free" },
  { name: "Gradients Guru", title: "Gradients Guru | Mesh & Linear Gradient Studio", url: "https://gradients.guru", cat: ["Color Tools & UI Design Systems"], desc: "Aesthetic collection of complex multi-color mesh gradients and noise backgrounds.", pricing: "Free" },
  { name: "Uncut Type", title: "Uncut.wtf | Contemporary Open-Source Typographic Showcase", url: "https://uncut.wtf", cat: ["Typography & Font Discovery"], desc: "Curated directory of experimental and open-source display typefaces.", pricing: "Free" },
  { name: "Ray.so Backgrounds", title: "Ray.so Backgrounds | Modern Wallpaper Generator", url: "https://ray.so/backgrounds", cat: ["Design Assets & Graphic Elements"], desc: "Generative tool that creates modern 4K desktop wallpapers and mesh gradients.", pricing: "Free" },
  { name: "Fontshare Font Pairs", title: "Fontshare Pairings | Curated Editorial Combinations", url: "https://www.fontshare.com/pairs", cat: ["Typography & Font Discovery"], desc: "Ready-to-use typography pairings matching headlines with readable body copy.", pricing: "Free" },
  { name: "Hover.dev Bento Grids", title: "Hover.dev Bento Grids | Animated React & Tailwind Cards", url: "https://www.hover.dev/components/bento-grids", cat: ["Component Libraries & Design Systems"], desc: "Pre-built modular bento-box layouts animated with Framer Motion.", pricing: "Freemium" },
  { name: "Magic UI Bento", title: "Magic UI Bento Grid | Kinetic Layout Blocks", url: "https://magicui.design/docs/components/bento-grid", cat: ["Animation & Frontend Frameworks"], desc: "Bento Grid components featuring kinetic micro-animations and animated SVG backgrounds.", pricing: "Free" },
  { name: "Lucide Studio", title: "Lucide Studio | Vector Icon Customizer", url: "https://lucide.dev/icons", cat: ["Vector Graphics & Iconography"], desc: "Interactive web interface to search, filter, and customize over 1,400 icons.", pricing: "Free" },
  { name: "TinyPNG", title: "TinyPNG | Smart WebP and PNG Compression", url: "https://tinypng.com", cat: ["Image Optimization & Performance"], desc: "Smart lossy compression techniques to drastically reduce image file sizes.", pricing: "Free" },

  // --- BATCH 11: FULL STACK & FRAMEWORKS ---
  { name: "Fontsource", title: "Fontsource | Self-Hosted Open-Source Web Fonts", url: "https://fontsource.org", cat: ["Typography & Font Discovery"], desc: "Fontsource packages open-source Google Fonts and independent typefaces into self-contained npm packages.", pricing: "Free" },
  { name: "Vite", title: "Vite | Next-Generation Frontend Build Tool", url: "https://vitejs.dev", cat: ["Developer Tooling & JavaScript Runtimes"], desc: "Vite is a fast frontend build tool and local development server created by Evan You.", pricing: "Free" },
  { name: "Nuxt", title: "Nuxt | The Intuitive Vue Full-Stack Framework", url: "https://nuxt.com", cat: ["Frontend Frameworks & Full-Stack Systems"], desc: "Nuxt is an open-source framework that builds full-stack, server-side rendered, and statically generated web applications on top of Vue 3.", pricing: "Free" },
  { name: "Svelte", title: "Svelte | Cybernetically Enhanced Web Apps", url: "https://svelte.dev", cat: ["Frontend Frameworks & Full-Stack Systems"], desc: "Svelte is a component framework that shifts the heavy lifting of UI rendering from the client browser to the compile step.", pricing: "Free" },
  { name: "Astro", title: "Astro | The Web Framework for Content-Driven Websites", url: "https://astro.build", cat: ["Frontend Frameworks & Full-Stack Systems"], desc: "Astro is a web framework engineered for content-rich websites such as blogs, marketing portals, and e-commerce stores.", pricing: "Free" },
  { name: "Remix", title: "Remix | Focused on Web Standards and Modern UX", url: "https://remix.run", cat: ["Frontend Frameworks & Full-Stack Systems"], desc: "Remix is a full-stack React framework centered on native web standards and HTTP caching.", pricing: "Free" },
  { name: "SolidJS", title: "SolidJS | Simple and Performant Reactivity", url: "https://www.solidjs.com", cat: ["Frontend Frameworks & Full-Stack Systems"], desc: "SolidJS is a declarative, fine-grained reactive JavaScript library for building user interfaces without a Virtual DOM.", pricing: "Free" },
  { name: "Heroicons", title: "Heroicons | Hand-Crafted SVG Icons by Tailwind Labs", url: "https://heroicons.com", cat: ["Vector Graphics & Iconography"], desc: "Heroicons is a library of free, hand-crafted SVG vector icons designed by the creators of Tailwind CSS.", pricing: "Free" },
  { name: "Simple Icons", title: "Simple Icons | Free SVG Icons for Popular Brands", url: "https://simpleicons.org", cat: ["Design Assets & Brand Logos"], desc: "Simple Icons is an open-source collection containing over 3,000 brand, software, and company vector SVG logos.", pricing: "Free" },
  { name: "Unsplash Collections", title: "Unsplash Curated Sets | Thematic Photography Archives", url: "https://unsplash.com/collections", cat: ["Stock Photography & Visual Assets"], desc: "The Unsplash Collections index organizes millions of high-resolution royalty-free photographs into specific thematic sets.", pricing: "Free" },
  { name: "Radix UI", title: "Radix Primitives | Unstyled, Accessible UI Components for React", url: "https://www.radix-ui.com", cat: ["Component Libraries & Design Systems"], desc: "Radix Primitives is an open-source React component library designed to serve as the unstyled, accessible foundation for custom design systems.", pricing: "Free" },
  { name: "Tailwind Typography", title: "Tailwind Typography | Prose Styling for Markdown and CMS Content", url: "https://tailwindcss-typography.vercel.app", cat: ["Frontend Frameworks & Styling Tooling"], desc: "Tailwind Typography is the official plugin that adds a set of 'prose' utility classes to style untagged HTML content.", pricing: "Free" },
  { name: "Turborepo", title: "Turborepo | High-Performance Monorepo Build System", url: "https://turbo.build/repo", cat: ["Developer Utilities & Code Quality"], desc: "Turborepo is an incremental build system written in Rust designed for JavaScript and TypeScript monorepos.", pricing: "Free" },
  { name: "Appwrite", title: "Appwrite | Open-Source Secure Backend Server for Web & Mobile", url: "https://appwrite.io", cat: ["Cloud Backend & Database Infrastructure"], desc: "Appwrite is an open-source, self-hostable backend-as-a-service platform that provides developers with authentication and databases.", pricing: "Free" },
  { name: "Neon", title: "Neon | Serverless Multi-Cloud PostgreSQL with Instant Branching", url: "https://neon.tech", cat: ["Cloud Databases & Data Infrastructure"], desc: "Neon is a serverless PostgreSQL database platform that separates compute from storage.", pricing: "Freemium" },
  { name: "PostHog Replay", title: "PostHog Session Replay | Visual User Session Playback", url: "https://posthog.com/session-replay", cat: ["Analytics & User Behavior"], desc: "PostHog's Session Replay module provides high-fidelity, interactive playback of real user interactions on your website.", pricing: "Freemium" },
  { name: "Directus", title: "Directus | Open-Source Headless Data Engine & API Wrapper", url: "https://directus.io", cat: ["Backend APIs & Data Orchestration"], desc: "Directus is a real-time data engine that layers instant REST and GraphQL APIs directly on top of any SQL database.", pricing: "Free" },
  { name: "Plausible", title: "Plausible Analytics | Lightweight & Privacy-Friendly Web Metrics", url: "https://plausible.io", cat: ["Analytics & User Behavior"], desc: "Plausible is an open-source, privacy-first web analytics platform that provides essential traffic insights.", pricing: "Paid" },
  { name: "Svgl Icons", title: "Svgl Tech Stack Icons | Curated Developer Library", url: "https://svgl.app/directory", cat: ["Design Assets & Brand Logos"], desc: "The Svgl Directory provides an interface to search, preview, and download optimized SVG vectors for modern technology.", pricing: "Free" },
  { name: "Payload CMS", title: "Payload CMS | Code-First Native TypeScript Headless CMS", url: "https://payloadcms.com", cat: ["No-Code & Web Architecture"], desc: "Payload is a code-first, open-source headless CMS and application framework built on TypeScript.", pricing: "Free" },
  { name: "Trigger.dev V3", title: "Trigger.dev Realtime | Serverless Background Event Streams", url: "https://trigger.dev/realtime", cat: ["Cloud Infrastructure & Background Tasks"], desc: "Trigger.dev Realtime provides an event-driven infrastructure to execute long-running AI pipelines and tasks.", pricing: "Freemium" },

  // --- BATCH 12: HOBBY & ENTHUSIAST ---
  { name: "Lichess", title: "Lichess | Free, Open-Source Online Chess", url: "https://lichess.org", cat: ["Chess & Board Games"], desc: "Lichess is an entirely free, open-source, ad-free online chess platform supported by community donations.", pricing: "Free" },
  { name: "Chess.com", title: "Chess.com | Play Chess Online & Master Strategy", url: "https://www.chess.com", cat: ["Chess & Board Games"], desc: "Chess.com is the world's largest online chess community and training platform.", pricing: "Freemium" },
  { name: "Board Game Arena", title: "Board Game Arena | Play Tabletop Games Online", url: "https://boardgamearena.com", cat: ["Tabletop & Board Games"], desc: "Board Game Arena is a browser-based digital tabletop gaming platform that lets you play hundreds of licensed board games.", pricing: "Freemium" },
  { name: "BandLab", title: "BandLab | Cloud Music Creation Studio & Community", url: "https://www.bandlab.com", cat: ["Music Production & Audio Creation"], desc: "BandLab is a cloud-based digital audio workstation (DAW) that enables musicians to record, mix, and collaborate.", pricing: "Free" },
  { name: "Soundation", title: "Soundation | In-Browser Beatmaker & Music Studio", url: "https://soundation.com", cat: ["Music Production & Audio Creation"], desc: "Soundation is an online music production studio that lets producers collaborate on beats and electronic tracks.", pricing: "Freemium" },
  { name: "Soundtrap", title: "Soundtrap by Spotify | Collaborative Online DAW", url: "https://www.soundtrap.com", cat: ["Music Production & Audio Creation"], desc: "Soundtrap is Spotify's online collaborative recording studio designed for songwriting and beat making.", pricing: "Freemium" },
  { name: "Audiotool", title: "Audiotool | Collaborative Modular Synthesizer Studio", url: "https://www.audiotool.com", cat: ["Music Production & Audio Creation"], desc: "Audiotool is a browser-based music studio modeled after physical vintage hardware with real-time cloud collaboration.", pricing: "Free" },
  { name: "Tinkercad", title: "Tinkercad | Simple 3D Design & Electronics Circuits", url: "https://www.tinkercad.com", cat: ["3D Printing & Electronics Tinkering"], desc: "Tinkercad is a free, web-based 3D modeling and circuit simulation suite created by Autodesk.", pricing: "Free" },
  { name: "Printables", title: "Printables | 3D Printing Model Database by Prusa", url: "https://www.printables.com", cat: ["3D Printing & Maker Projects"], desc: "Printables is a community-driven database of free 3D printable STL and G-code models run by Prusa Research.", pricing: "Free" },
  { name: "Thingiverse", title: "Thingiverse | Open Community for 3D Printable Hardware", url: "https://www.thingiverse.com", cat: ["3D Printing & Maker Projects"], desc: "Thingiverse is one of the internet's largest and oldest open-source 3D model repositories.", pricing: "Free" },
  { name: "Instructables", title: "Instructables | DIY Projects, Making & Craft Guides", url: "https://www.instructables.com", cat: ["DIY Crafting & Maker Projects"], desc: "Instructables is a community platform dedicated to step-by-step DIY tutorials and maker projects.", pricing: "Free" },
  { name: "Hackaday", title: "Hackaday | Fresh Hardware Hacks & Engineering Projects", url: "https://hackaday.com", cat: ["Electronics & Hardware Hacking"], desc: "Hackaday is an editorial hub showcasing creative engineering hacks, custom micro-controller builds, and vintage tech restoration.", pricing: "Free" },
  { name: "Wokwi", title: "Wokwi | Online Arduino, ESP32 & Raspberry Pi Simulator", url: "https://wokwi.com", cat: ["Electronics & Hardware Hacking"], desc: "Wokwi is an in-browser hardware simulator for Arduino, ESP32, STM32, and Raspberry Pi Pico boards.", pricing: "Free" },
  { name: "Stellarium Web", title: "Stellarium Web | Interactive Virtual Planetarium", url: "https://stellarium-web.org", cat: ["Astronomy & Stargazing"], desc: "Stellarium Web is a realistic, interactive planetarium that maps the night sky in real time.", pricing: "Free" },
  { name: "AstroBin", title: "AstroBin | Global Astrophotography Image Archive", url: "https://www.astrobin.com", cat: ["Astronomy & Astrophotography"], desc: "AstroBin is a specialized photo-hosting platform and community built exclusively for astrophotographers.", pricing: "Freemium" },
  { name: "eBird", title: "eBird | Global Birdwatching & Sightings Database", url: "https://ebird.org", cat: ["Birdwatching & Nature Exploration"], desc: "eBird is a global citizen-science birdwatching platform managed by the Cornell Lab of Ornithology.", pricing: "Free" },
  { name: "iNaturalist", title: "iNaturalist | Plant, Animal & Insect Identification", url: "https://www.inaturalist.org", cat: ["Nature & Wildlife Observation"], desc: "iNaturalist is a social network for naturalists that helps identify wild plants, animals, insects, and fungi.", pricing: "Free" },
  { name: "AllTrails", title: "AllTrails | Trail Maps for Hiking, Running & Biking", url: "https://www.alltrails.com", cat: ["Hiking & Outdoor Recreation"], desc: "AllTrails is a comprehensive outdoor trail guide featuring over 400,000 curated trail maps.", pricing: "Freemium" },
  { name: "Geocaching", title: "Geocaching | The World's Largest Real-World Treasure Hunt", url: "https://www.geocaching.com", cat: ["Outdoor Exploration & Geocaching"], desc: "Geocaching is the official portal for real-world outdoor treasure hunting using GPS coordinates.", pricing: "Freemium" },
  { name: "Duolingo", title: "Duolingo | Gamified Language Learning", url: "https://www.duolingo.com", cat: ["Language Learning"], desc: "Duolingo makes learning new languages accessible through bite-sized, gamified daily lessons.", pricing: "Freemium" },
  { name: "Forvo", title: "Forvo | The Pronunciation Dictionary of the World", url: "https://forvo.com", cat: ["Language Learning"], desc: "Forvo is the world's largest pronunciation guide, containing millions of audio recordings by native speakers.", pricing: "Free" },
  { name: "Goodreads", title: "Goodreads | Book Tracking, Reviews & Recommendations", url: "https://www.goodreads.com", cat: ["Reading & Book Collecting"], desc: "Goodreads is the premier social platform for book lovers, readers, and collectors.", pricing: "Free" },
  { name: "StoryGraph", title: "The StoryGraph | Modern Book Tracking & Mood Filters", url: "https://www.thestorygraph.com", cat: ["Reading & Book Collecting"], desc: "The StoryGraph is an independent reading tracker that delivers in-depth reading statistics and mood filters.", pricing: "Freemium" },
  { name: "Discogs", title: "Discogs | Vinyl Record & Music Collector Database", url: "https://www.discogs.com", cat: ["Vinyl & Music Collecting"], desc: "Discogs is the definitive database and international marketplace for physical music media like vinyl records.", pricing: "Free" },
  { name: "Untappd", title: "Untappd | Craft Beer Discovery & Check-in Network", url: "https://untappd.com", cat: ["Craft Brewing & Beverage Tasting"], desc: "Untappd is a social network and tasting journal for craft beer enthusiasts.", pricing: "Free" },
  { name: "Vivino", title: "Vivino | Wine Scanner, Ratings & Taste Profiles", url: "https://www.vivino.com", cat: ["Wine Tasting & Sommelier Skills"], desc: "Vivino is a wine discovery platform that uses photo label scanning to deliver instant community ratings.", pricing: "Free" },
  { name: "Serious Eats", title: "Serious Eats | Science-Backed Culinary Techniques & Recipes", url: "https://www.seriouseats.com", cat: ["Cooking & Culinary Arts"], desc: "Serious Eats is a culinary education hub focused on the food science behind home cooking.", pricing: "Free" },
  { name: "NYT Cooking", title: "NYT Cooking | Curated Recipes & Home Cooking Community", url: "https://cooking.nytimes.com", cat: ["Cooking & Culinary Arts"], desc: "NYT Cooking is a curated digital cookbook featuring thousands of professional tested recipes.", pricing: "Paid" },
  { name: "Bake with Jack", title: "Bake with Jack | Artisanal Bread Making & Sourdough Guides", url: "https://www.bakewithjack.co.uk", cat: ["Baking & Sourdough Craft"], desc: "Bake with Jack is an educational bread-making portal run by professional baker Jack Sturgess.", pricing: "Free" },
  { name: "Ravelry", title: "Ravelry | Community for Knitters, Crocheters & Fiber Artists", url: "https://www.ravelry.com", cat: ["Knitting & Fiber Arts"], desc: "Ravelry is an extensive database and social platform for knitting, crocheting, and weaving enthusiasts.", pricing: "Free" },
  { name: "Sewing.org", title: "Sewing.org | Free Sewing Patterns, Techniques & Guidelines", url: "https://www.sewing.org", cat: ["Sewing & Garment Craft"], desc: "Sewing.org is an educational resource hub offering free patterns and alteration tutorials.", pricing: "Free" },
  { name: "BoardGameGeek", title: "BoardGameGeek | The Tabletop Gaming Database", url: "https://boardgamegeek.com", cat: ["Tabletop & Board Games"], desc: "BoardGameGeek (BGG) is the authoritative encyclopedia and community forum for tabletop hobbyists.", pricing: "Free" },
  { name: "D&D Beyond", title: "D&D Beyond | Official Digital Dungeons & Dragons Toolkit", url: "https://www.dndbeyond.com", cat: ["Tabletop RPGs & Storytelling"], desc: "D&D Beyond is the official digital companion suite for Dungeons & Dragons 5th Edition.", pricing: "Freemium" },
  { name: "Roll20", title: "Roll20 | Virtual Tabletop for Pen & Paper RPGs", url: "https://roll20.net", cat: ["Tabletop RPGs & Storytelling"], desc: "Roll20 is a browser-based virtual tabletop (VTT) that brings tabletop roleplaying games online.", pricing: "Freemium" },
  { name: "ChessTempo", title: "ChessTempo | Advanced Chess Tactics & Endgame Training", url: "https://chesstempo.com", cat: ["Chess & Board Games"], desc: "ChessTempo is a specialized chess improvement website focused on tactical calculation and endgame mastery.", pricing: "Freemium" },
  { name: "Plantnet", title: "PlantNet | Citizen Science Plant Identification", url: "https://identify.plantnet.org", cat: ["Gardening & Plant Care"], desc: "PlantNet is a visual botanical identification tool developed by scientists to identify wild species.", pricing: "Free" },
  { name: "Gardenize", title: "Gardenize | Digital Plant Diary & Garden Planner", url: "https://gardenize.com", cat: ["Gardening & Plant Care"], desc: "Gardenize is a digital gardening journal and planning platform for indoor and outdoor plants.", pricing: "Freemium" },
  { name: "JustinGuitar", title: "JustinGuitar | Comprehensive Free Guitar Lessons", url: "https://www.justinguitar.com", cat: ["Musical Instruments & Guitar"], desc: "JustinGuitar is a structured guitar education platform featuring hundreds of free video lessons.", pricing: "Free" },
  { name: "Songsterr", title: "Songsterr | Interactive Guitar, Bass & Drum Tabs", url: "https://www.songsterr.com", cat: ["Musical Instruments & Guitar"], desc: "Songsterr is an interactive online tablature player featuring over 800,000 tabs.", pricing: "Freemium" },
  { name: "Flat.io", title: "Flat.io | Collaborative Online Music Sheet Notation", url: "https://flat.io", cat: ["Music Theory & Composition"], desc: "Flat.io is an intuitive, collaborative music notation software that runs in your web browser.", pricing: "Freemium" },
  { name: "Musenet", title: "Musenet | Interactive Music Theory & Ear Training", url: "https://www.musictheory.net", cat: ["Music Theory & Composition"], desc: "MusicTheory.net provides interactive web exercises and tutorials for learning music theory.", pricing: "Free" },
  { name: "PuzzGrid", title: "PuzzGrid | Only Connect-Style Connecting Wall Puzzles", url: "https://puzzgrid.com", cat: ["Puzzles & Trivia"], desc: "PuzzGrid is an interactive puzzle website inspired by the British television show Only Connect.", pricing: "Free" },
  { name: "Sporcle", title: "Sporcle | Mentally Stimulating Trivia & Quiz Arcade", url: "https://www.sporcle.com", cat: ["Puzzles & Trivia"], desc: "Sporcle is the internet's largest trivia website, hosting hundreds of thousands of timed quizzes.", pricing: "Freemium" },
  { name: "Worldle", title: "Worldle | Daily Geographic Map Outline Quiz", url: "https://worldle.teuteuf.fr", cat: ["Geography & Map Games"], desc: "Worldle is a daily geography puzzle game where players identify mystery territories by silhouette.", pricing: "Free" },
  { name: "Origami.me", title: "Origami.me | Paper Folding Diagrams & Guides", url: "https://origami.me", cat: ["Origami & Papercraft"], desc: "Origami.me is a dedicated paper-folding resource offering step-by-step diagrams and guides.", pricing: "Free" },
  { name: "BrickLink", title: "BrickLink | The Unofficial LEGO Marketplace & Studio", url: "https://www.bricklink.com", cat: ["LEGO Building & Model Collecting"], desc: "BrickLink is the world's largest marketplace and catalogue dedicated to genuine LEGO bricks.", pricing: "Free" },
  { name: "Rebrickable", title: "Rebrickable | Build New Custom MOCs from Your LEGO Sets", url: "https://rebrickable.com", cat: ["LEGO Building & Model Collecting"], desc: "Rebrickable matches the LEGO sets you own against user-submitted custom build instructions.", pricing: "Freemium" },
  { name: "FlightAware", title: "FlightAware | Live Flight Tracking & Aviation Telemetry", url: "https://flightaware.com", cat: ["Aviation & Plane Spotting"], desc: "FlightAware is an enterprise-grade flight tracking data platform for aviation enthusiasts and pilots.", pricing: "Freemium" },
  { name: "MarineTraffic", title: "MarineTraffic | Live Global Ship Tracking & AIS Maps", url: "https://www.marinetraffic.com", cat: ["Maritime & Ship Spotting"], desc: "MarineTraffic tracks real-time global maritime vessel movements using land-based transponders.", pricing: "Freemium" },
  { name: "Letterboxd", title: "Letterboxd | Social Film Diary & Cinephile Community", url: "https://letterboxd.com", cat: ["Film & Cinema Appreciation"], desc: "Letterboxd is a social platform for cinema lovers to log films, write reviews, and rate movies.", pricing: "Freemium" },
];

export const MOCK_WEBSITES: Website[] = Array.from(new Set(RAW_SITES.map(s => s.url)))
  .map((url, index) => {
    const site = RAW_SITES.find(s => s.url === url)!;
    const pricing = site.pricing || "Free";

    return {
      id: `site-${index}`,
      name: (site as any).title || site.name, // Discovery Title
      websiteName: site.name, // Brand Name
      developer: (site as any).developer || "Bessites Curator",
      description: site.desc || (site as any).description, // Detailed Info
      longDescription: site.desc || (site as any).description,
      rating: 4.5 + (Math.random() * 0.5),
      reviewCount: 12 + Math.floor(Math.random() * 100),
      categories: site.cat || (site as any).categories || [],
      imageUrl: "", 
      screenshots: [],
      url: site.url,
      size: "N/A",
      version: "1.0",
      updatedAt: "2024",
      pricing: pricing as any,
      pros: (site as any).pros || ["Hand-picked quality", "Verified URL", "Highly useful"],
      cons: (site as any).cons || ["May require account", "Limited free tier"],
      bestFor: (site as any).bestFor || "General users and digital creators."
    };
  });
