
export interface Website {
  id: string;
  name: string;
  developer: string;
  description: string;
  longDescription: string;
  rating: number;
  reviewCount: number;
  categories: string[];
  imageUrl: string;
  imageHint: string;
  screenshots: string[];
  isSponsored?: boolean;
  url: string;
  size: string;
  version: string;
  updatedAt: string;
  pricing: "Free" | "Paid" | "Freemium";
}

export const MOCK_WEBSITES: Website[] = [
  {
    id: "loot-drop",
    name: "Loot Drop",
    developer: "Gaming Hub",
    description: "The ultimate vault for gamers and drops.",
    longDescription: "Loot Drop helps gamers track limited-time offers, cosmetic drops, and digital collectibles across multiple platforms.",
    rating: 4.7,
    reviewCount: 3400,
    categories: ["Gaming", "Tools"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/loot/600/800",
    imageHint: "gaming interface",
    screenshots: ["https://picsum.photos/seed/loot1/800/600"],
    url: "https://lootdrop.io",
    size: "Web-based",
    version: "1.4.2",
    updatedAt: "Feb 15, 2024"
  },
  {
    id: "emojikitchen",
    name: "Emoji Kitchen",
    developer: "Google",
    description: "Mix and mash your favorite emojis.",
    longDescription: "A delightful browser-based version of Google's famous Gboard feature. Combine two different emojis to create hundreds of unique stickers.",
    rating: 4.9,
    reviewCount: 12500,
    categories: ["Fun", "Creative"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/emoji/600/900",
    imageHint: "emoji mashup",
    screenshots: ["https://picsum.photos/seed/emoji1/800/600"],
    url: "https://emojikitchen.com",
    size: "N/A",
    version: "2.0.0",
    updatedAt: "Jan 10, 2024"
  },
  {
    id: "dofsimulator",
    name: "Dofsimulator",
    developer: "Michael Vane",
    description: "Professional depth of field calculator.",
    longDescription: "An essential tool for photographers and cinematographers. Calculate bokeh and depth of field with high accuracy.",
    rating: 4.8,
    reviewCount: 2100,
    categories: ["Photography", "Tools"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/camera/600/600",
    imageHint: "camera lens",
    screenshots: ["https://picsum.photos/seed/cam1/800/600"],
    url: "https://dofsimulator.net",
    size: "5MB",
    version: "3.5.1",
    updatedAt: "Mar 02, 2024"
  },
  {
    id: "carcarekiosk",
    name: "CarCareKiosk",
    developer: "Auto Solutions",
    description: "Step-by-step DIY car repair videos.",
    longDescription: "Access thousands of free videos showing you exactly how to fix your specific car. From changing headlight bulbs to cabin air filters.",
    rating: 4.6,
    reviewCount: 8900,
    categories: ["Automotive", "Education"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/car/600/700",
    imageHint: "car repair",
    screenshots: ["https://picsum.photos/seed/car1/800/600"],
    url: "https://carcarekiosk.com",
    size: "N/A",
    version: "Web-app",
    updatedAt: "Dec 20, 2023"
  },
  {
    id: "modsnation",
    name: "Modsnation",
    developer: "Modding Collective",
    description: "The global hub for game modifications.",
    longDescription: "Explore and download the latest mods for your favorite PC games. Modsnation provides a safe and organized platform for creators.",
    rating: 4.4,
    reviewCount: 5600,
    categories: ["Gaming", "Tech"],
    pricing: "Freemium",
    imageUrl: "https://picsum.photos/seed/mods/600/800",
    imageHint: "game mods",
    screenshots: ["https://picsum.photos/seed/mods1/800/600"],
    url: "https://modsnation.com",
    size: "Var",
    version: "1.0.4",
    updatedAt: "Feb 28, 2024"
  },
  {
    id: "kartbros",
    name: "KartBros",
    developer: "Retro Studios",
    description: "Multiplayer kart racing in your browser.",
    longDescription: "A fast-paced, 3D kart racing game that runs directly in your browser. Compete with players worldwide.",
    rating: 4.3,
    reviewCount: 4200,
    categories: ["Gaming", "Fun"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/kart/600/900",
    imageHint: "kart racing",
    screenshots: ["https://picsum.photos/seed/kart1/800/600"],
    url: "https://kartbros.com",
    size: "15MB",
    version: "0.8.9-beta",
    updatedAt: "Mar 05, 2024"
  },
  {
    id: "tenasa",
    name: "Tenasa",
    developer: "Tenasa Systems",
    description: "Modern project management for agile teams.",
    longDescription: "Tenasa offers a clean, visual way to manage tasks and projects with Gantt charts and time tracking.",
    rating: 4.5,
    reviewCount: 1500,
    categories: ["Productivity", "Business"],
    pricing: "Paid",
    imageUrl: "https://picsum.photos/seed/tenasa/600/750",
    imageHint: "business dashboard",
    screenshots: ["https://picsum.photos/seed/ten1/800/600"],
    url: "https://tenasa.com",
    size: "Web-app",
    version: "2.1.0",
    updatedAt: "Jan 15, 2024"
  },
  {
    id: "delphi",
    name: "Delphi",
    developer: "Predictive AI",
    description: "AI-driven forecasting and prediction markets.",
    longDescription: "Delphi uses collective intelligence and machine learning to predict future events.",
    rating: 4.7,
    reviewCount: 3100,
    categories: ["AI", "Finance"],
    pricing: "Freemium",
    imageUrl: "https://picsum.photos/seed/delphi/600/800",
    imageHint: "data visualization",
    screenshots: ["https://picsum.photos/seed/del1/800/600"],
    url: "https://delphi.ai",
    size: "N/A",
    version: "1.2.0",
    updatedAt: "Feb 12, 2024"
  },
  {
    id: "privnote",
    name: "Privnote",
    developer: "Privacy Labs",
    description: "Send notes that self-destruct after reading.",
    longDescription: "Privnote allows you to send confidential notes over the internet. The note is deleted the moment someone reads it.",
    rating: 4.9,
    reviewCount: 25000,
    categories: ["Privacy", "Tools"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/note/600/500",
    imageHint: "secret note",
    screenshots: ["https://picsum.photos/seed/note1/800/600"],
    url: "https://privnote.com",
    size: "Minimal",
    version: "Web-legacy",
    updatedAt: "Static",
    isSponsored: true
  },
  {
    id: "picular",
    name: "Picular",
    developer: "Future Memories",
    description: "The Google of colors.",
    longDescription: "Picular is a rocket fast primary color generator using Google's image search. Type any word to find its color.",
    rating: 4.8,
    reviewCount: 18000,
    categories: ["Design", "Creative"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/color/600/950",
    imageHint: "color palette",
    screenshots: ["https://picsum.photos/seed/pic1/800/600"],
    url: "https://picular.co",
    size: "Web",
    version: "3.0.1",
    updatedAt: "Nov 12, 2023"
  },
  {
    id: "redcoats",
    name: "Redcoats",
    developer: "Historical Games",
    description: "Revolutionary war strategy simulator.",
    longDescription: "Command troops in a detailed simulation of historical battles. Manage resources, terrain, and morale.",
    rating: 4.2,
    reviewCount: 950,
    categories: ["Gaming", "Strategy"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/battle/600/800",
    imageHint: "historical battle",
    screenshots: ["https://picsum.photos/seed/red1/800/600"],
    url: "https://redcoats.io",
    size: "12MB",
    version: "0.5.2",
    updatedAt: "Mar 10, 2024"
  },
  {
    id: "3dsvg",
    name: "3Dsvg",
    developer: "Vector Dimension",
    description: "Transform 2D SVGs into 3D models.",
    longDescription: "Upload your flat vector graphics and extrude them into 3D space instantly.",
    rating: 4.5,
    reviewCount: 2200,
    categories: ["Design", "3D"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/3d/600/600",
    imageHint: "3d modeling",
    screenshots: ["https://picsum.photos/seed/3d1/800/600"],
    url: "https://3dsvg.com",
    size: "Web-based",
    version: "2.4.0",
    updatedAt: "Jan 22, 2024"
  },
  {
    id: "storyset",
    name: "Storyset",
    developer: "Freepik",
    description: "Amazing free illustrations for your projects.",
    longDescription: "Edit and animate beautiful illustrations to use in your landing pages or apps.",
    rating: 4.9,
    reviewCount: 45000,
    categories: ["Design", "Creative"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/story/600/850",
    imageHint: "vector illustration",
    screenshots: ["https://picsum.photos/seed/story1/800/600"],
    url: "https://storyset.com",
    size: "Web",
    version: "1.8.0",
    updatedAt: "Feb 05, 2024"
  },
  {
    id: "eyecandy",
    name: "Eyecandy",
    developer: "Visual Labs",
    description: "A library of the best visual effects in film.",
    longDescription: "Curated collection of cinematic shots and visual techniques for directors and editors.",
    rating: 4.7,
    reviewCount: 5600,
    categories: ["Design", "Video"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/candy/600/900",
    imageHint: "cinematic shot",
    screenshots: ["https://picsum.photos/seed/eye1/800/600"],
    url: "https://eyecandy.cm",
    size: "N/A",
    version: "Archive",
    updatedAt: "Weekly"
  },
  {
    id: "entertrained",
    name: "Entertrained",
    developer: "LearnFlow",
    description: "Level up your skills with gamified training.",
    longDescription: "Entertrained turns complex technical subjects into interactive games to learn faster.",
    rating: 4.4,
    reviewCount: 1200,
    categories: ["Education", "Gaming"],
    pricing: "Freemium",
    imageUrl: "https://picsum.photos/seed/train/600/700",
    imageHint: "educational game",
    screenshots: ["https://picsum.photos/seed/ent1/800/600"],
    url: "https://entertrained.com",
    size: "Web",
    version: "1.0.1",
    updatedAt: "Dec 15, 2023"
  },
  {
    id: "toontone",
    name: "Toontone",
    developer: "Audio Fun",
    description: "Professional cartoon voice generator.",
    longDescription: "Apply studio-quality cartoon filters to your voice in real-time for streaming.",
    rating: 4.1,
    reviewCount: 850,
    categories: ["Audio", "Fun"],
    pricing: "Paid",
    imageUrl: "https://picsum.photos/seed/toon/600/600",
    imageHint: "cartoon voice",
    screenshots: ["https://picsum.photos/seed/toon1/800/600"],
    url: "https://toontone.com",
    size: "8MB",
    version: "2.2.0",
    updatedAt: "Feb 14, 2024"
  },
  {
    id: "paperme",
    name: "Paperme",
    developer: "Creative Origami",
    description: "Digital patterns for physical paper crafts.",
    longDescription: "Choose from hundreds of paper craft patterns, customize their scale, and print them out.",
    rating: 4.6,
    reviewCount: 2400,
    categories: ["Lifestyle", "Creative"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/paper/600/800",
    imageHint: "paper craft",
    screenshots: ["https://picsum.photos/seed/paper1/800/600"],
    url: "https://paperme.com",
    size: "Web",
    version: "0.9.5",
    updatedAt: "Jan 05, 2024"
  },
  {
    id: "workout",
    name: "Workout",
    developer: "FitTech",
    description: "Your browser-based personal trainer.",
    longDescription: "Use your webcam for posture correction and follow guided HIIT sessions anywhere.",
    rating: 4.5,
    reviewCount: 6700,
    categories: ["Health", "Fitness"],
    pricing: "Freemium",
    imageUrl: "https://picsum.photos/seed/gym/600/850",
    imageHint: "fitness training",
    screenshots: ["https://picsum.photos/seed/work1/800/600"],
    url: "https://workout.com",
    size: "Web",
    version: "4.2.1",
    updatedAt: "Mar 01, 2024"
  },
  {
    id: "hotkeycheatsheet",
    name: "Hotkeycheatsheet",
    developer: "Pro Shortcuts",
    description: "The ultimate database for app shortcuts.",
    longDescription: "Quickly find the keyboard shortcuts for over 1000 professional applications.",
    rating: 4.8,
    reviewCount: 15000,
    categories: ["Productivity", "Tools"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/keys/600/500",
    imageHint: "keyboard shortcuts",
    screenshots: ["https://picsum.photos/seed/keys1/800/600"],
    url: "https://hotkeycheatsheet.com",
    size: "Lightweight",
    version: "Archive",
    updatedAt: "Daily"
  },
  {
    id: "123apps",
    name: "123Apps",
    developer: "Web Tool Suite",
    description: "All-in-one web apps for file editing.",
    longDescription: "A massive collection of tools for video editing, audio manipulation, and PDF conversion.",
    rating: 4.7,
    reviewCount: 89000,
    categories: ["Tools", "Utility"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/apps/600/750",
    imageHint: "web tools",
    screenshots: ["https://picsum.photos/seed/apps1/800/600"],
    url: "https://123apps.com",
    size: "Web",
    version: "5.0.0",
    updatedAt: "Feb 20, 2024"
  },
  {
    id: "neal",
    name: "Neal.fun",
    developer: "Neal Agarwal",
    description: "A playground of internet wonders.",
    longDescription: "A collection of beautiful, funny, and thought-provoking web experiments.",
    rating: 5.0,
    reviewCount: 250000,
    categories: ["Fun", "Art"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/fun/600/900",
    imageHint: "internet experiments",
    screenshots: ["https://picsum.photos/seed/neal1/800/600"],
    url: "https://neal.fun",
    size: "Variable",
    version: "Hub",
    updatedAt: "Monthly",
    isSponsored: true
  },
  {
    id: "tinkercad",
    name: "Tinkercad",
    developer: "Autodesk",
    description: "Design and code in 3D.",
    longDescription: "The easiest way for beginners to get started with 3D design and electronics.",
    rating: 4.8,
    reviewCount: 45000,
    categories: ["Education", "Design"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/cad/600/800",
    imageHint: "3d design tool",
    screenshots: ["https://picsum.photos/seed/cad1/800/600"],
    url: "https://tinkercad.com",
    size: "Web-based",
    version: "2024.1",
    updatedAt: "Feb 01, 2024"
  },
  {
    id: "buildcores",
    name: "BuildCores",
    developer: "BuildCores Inc",
    description: "PC building and part comparison.",
    longDescription: "Plan your next PC build with ease and check compatibility between parts.",
    rating: 4.6,
    reviewCount: 3200,
    categories: ["Tech", "Tools"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/pc/600/700",
    imageHint: "pc components",
    screenshots: ["https://picsum.photos/seed/build1/800/600"],
    url: "https://buildcores.com",
    size: "Web",
    version: "2.1.2",
    updatedAt: "Jan 12, 2024"
  },
  {
    id: "funesworld",
    name: "Funesworld",
    developer: "Memory Labs",
    description: "Interactive world memory engine.",
    longDescription: "Explore historical events through a visual, connected memory web across centuries.",
    rating: 4.3,
    reviewCount: 600,
    categories: ["Education", "Culture"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/history/600/850",
    imageHint: "historical web",
    screenshots: ["https://picsum.photos/seed/funes1/800/600"],
    url: "https://funesworld.com",
    size: "Web",
    version: "1.0.0-rc",
    updatedAt: "Mar 11, 2024"
  },
  {
    id: "deadshot",
    name: "Deadshot",
    developer: "Aim Academy",
    description: "Professional FPS aim training.",
    longDescription: "The most precise browser-based aim trainer for competitive gamers.",
    rating: 4.7,
    reviewCount: 12000,
    categories: ["Gaming", "Tools"],
    pricing: "Freemium",
    imageUrl: "https://picsum.photos/seed/aim/600/800",
    imageHint: "fps crosshair",
    screenshots: ["https://picsum.photos/seed/dead1/800/600"],
    url: "https://deadshot.io",
    size: "18MB",
    version: "2.5.0",
    updatedAt: "Feb 22, 2024"
  },
  {
    id: "movewalls",
    name: "Movewalls",
    developer: "Dynamic Art",
    description: "Live wallpapers for your workspace.",
    longDescription: "Generate stunning live wallpapers that respond to your mouse movement.",
    rating: 4.4,
    reviewCount: 2100,
    categories: ["Design", "Personalization"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/wall/600/600",
    imageHint: "dynamic wallpaper",
    screenshots: ["https://picsum.photos/seed/move1/800/600"],
    url: "https://movewalls.com",
    size: "Web",
    version: "1.1.0",
    updatedAt: "Jan 18, 2024"
  },
  {
    id: "zperiod",
    name: "Zperiod",
    developer: "Focus Labs",
    description: "Deep work timer for professionals.",
    longDescription: "A distraction-free focus timer that helps you enter 'the zone' with ambient sounds.",
    rating: 4.8,
    reviewCount: 4500,
    categories: ["Productivity", "Health"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/time/600/750",
    imageHint: "focus timer",
    screenshots: ["https://picsum.photos/seed/zper1/800/600"],
    url: "https://zperiod.com",
    size: "Web",
    version: "2.0.0",
    updatedAt: "Feb 10, 2024"
  },
  {
    id: "shadergradient",
    name: "Shadergradient",
    developer: "Design Tools",
    description: "Create stunning 3D moving gradients.",
    longDescription: "A powerful tool for designers to create mesh gradients and moving backgrounds.",
    rating: 4.9,
    reviewCount: 8600,
    categories: ["Design", "Creative"],
    pricing: "Freemium",
    imageUrl: "https://picsum.photos/seed/gradient/600/800",
    imageHint: "abstract gradient",
    screenshots: ["https://picsum.photos/seed/shad1/800/600"],
    url: "https://shadergradient.co",
    size: "N/A",
    version: "3.2.1",
    updatedAt: "Mar 05, 2024"
  },
  {
    id: "jetpunk",
    name: "Jetpunk",
    developer: "Quiz Masters",
    description: "The world's best trivia and quizzes.",
    longDescription: "Test your knowledge on geography, history, and more with thousands of quizzes.",
    rating: 4.7,
    reviewCount: 450000,
    categories: ["Education", "Fun"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/quiz/600/950",
    imageHint: "trivia map",
    screenshots: ["https://picsum.photos/seed/jet1/800/600"],
    url: "https://jetpunk.com",
    size: "Web",
    version: "Live",
    updatedAt: "Daily"
  },
  {
    id: "autodraw",
    name: "Autodraw",
    developer: "Google Creative Lab",
    description: "AI-powered drawing tool for everyone.",
    longDescription: "AutoDraw pairs machine learning with drawings from talented artists to help you create visuals fast.",
    rating: 4.9,
    reviewCount: 120000,
    categories: ["AI", "Creative"],
    pricing: "Free",
    imageUrl: "https://picsum.photos/seed/draw/600/800",
    imageHint: "ai drawing",
    screenshots: ["https://picsum.photos/seed/auto1/800/600"],
    url: "https://autodraw.com",
    size: "Web",
    version: "1.0",
    updatedAt: "Oct 2023",
    isSponsored: true
  }
];
